name: wksctl
version: git
summary: Open Source Weaveworks Kubernetes System
description: >
  wksctl allows simple creation of a Kubernetes cluster given a set of IP addresses and an SSH key. It
  can be run in a standalone environment but is best used via a GitOps approach in which cluster and
  machine descriptions are stored in Git and the state of the cluster tracks changes to the descriptions.
   
  Its features include: simple creation of Kubernetes clusters, manage cluster and machine descriptions using Git,
  manage addons like Weave Net or Flux, Sealed Secret integration
# Needs to be able to read files passed as args, e.g. wksctl apply --machines, --cluster
confinement: classic
grade: stable
base: core18

parts:
  wksctl:
    source: .
    # Don't use go plugin because it doesn't seem to work with Go modules
    plugin: nil
    override-build: |
      export GOBIN=$SNAPCRAFT_PART_INSTALL/bin
      export VERSION=$(git tag -l | egrep -v '^(chart-|helm-|master-|pre-split|[a-z])' | sort --version-sort | tail -n1)
      go build -ldflags "-X github.com/weaveworks/wksctl/pkg/version.Version=$VERSION" -o $GOBIN/wksctl ./cmd/wksctl
    build-environment:
      - GO111MODULE: 'on'
      - CGO_ENABLED: '0'
    build-snaps:
      - go/1.12/stable

apps:
  wksctl:
    command: bin/wksctl
